### ISSUE TITLE
Cura won't save if end gcode comments contain some particular strings

### ISSUE THREAD

**Issue by MajorSlug** [Pheneeny/CuraPlugin-ScalableExtraPrime#2]
On Cura 3.2.1

When activated, it seems that the plugin interprets comments as valid gcode it should parse, and fails silently.

Add the current end Gcode setting to any printer then slice and try to save:
`G1 X1 Y280    ;move along X and Y` works
`G1 X1 Y280    ;move along X-Y` fails

Great plugin anyway! :)

**Comment by Pheneeny** [comment]
Thanks for submitting this issue. I apologize for the very delayed response, I did not have notifications setup properly in Github and was never notified of this issue. I have fixed the bug and will include it in the next release.
